print("Apex Visitor Check-In")
name = input("What is your name?:")
department = input("What is your department?:")
email = input("What is your email?:")
access = input("What is your access level?:")
print("+-------------------------------------+ ")
print("|          APEX ENTERTAINMENT PASS    |")
print("|-------------------------------------| ")
print("|Attendee : "+name.ljust(26)+"|")            
print("|ORG : "+department.ljust(31)+"|")        
print("|Contact : "+email.ljust(27)+"|")                   
print("|Acess : "+access.ljust(29)+"|")
print("|Issuer : BCH Software Terminal System|")
print("+-------------------------------------+")

